import Link from "next/link";
import { CalendarPlus, Clock3, Search } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { FollowUpStatusBadge } from "@/components/status-badge";
import { CustomerCell, DataTableShell, EmptyTableState, RowActionButtons, TableToolbar } from "@/components/tables/operational-table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { followUpStatusLabels, followUpStatuses, followUpTypeLabels, followUpTypes } from "@/constants/statuses";
import { getFollowUpDisplayStatus } from "@/lib/follow-ups";
import { formatSaudiDateTime } from "@/lib/format";
import { requireUser } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
type FollowUpsPageProps = { searchParams?: Record<string, string | string[] | undefined> };
type FollowUpRow = { id:string; customer_id:string; follow_up_type:string; scheduled_at:string; result:string|null; customers:{id:string; full_name:string; phone:string}|null; profiles:{full_name:string}|null; };
const tabs=[{key:"due_today",label:"اليوم"},{key:"overdue",label:"متأخرة"},{key:"upcoming",label:"قادمة"},{key:"completed",label:"مكتملة"},{key:"cancelled",label:"ملغاة"}] as const;
function param(searchParams: FollowUpsPageProps["searchParams"], key: string) { const value = searchParams?.[key]; return Array.isArray(value) ? value[0] ?? "" : value ?? ""; }
export default async function FollowUpsPage({ searchParams }: FollowUpsPageProps) { await requireUser(); const supabase=createClient(); const filters={employee:param(searchParams,"employeeId")||param(searchParams,"employee"),branch:param(searchParams,"branchId")||param(searchParams,"branch"),type:param(searchParams,"type"),status:param(searchParams,"status")||"due_today",date:param(searchParams,"date"),q:param(searchParams,"q")};
const [branchesResult,employeesResult]=await Promise.all([supabase.from("branches").select("id, name").eq("is_active", true).order("name"),supabase.from("profiles").select("id, full_name").eq("is_active", true).order("full_name")]);
let scopedCustomerIds:string[]|null=null; if(filters.branch||filters.q){let q=supabase.from("customers").select("id"); if(filters.branch) q=q.eq("branch_id",filters.branch); if(filters.q) q=q.or(`full_name.ilike.%${filters.q}%,phone.ilike.%${filters.q}%`); const {data}=await q.limit(500); scopedCustomerIds=(data??[]).map((c)=>c.id);}
let query=supabase.from("follow_ups").select("id, customer_id, assigned_employee_id, follow_up_type, scheduled_at, completed_at, result, status, customers(id, full_name, phone, branch_id), profiles!follow_ups_assigned_employee_id_fkey(full_name)").order("scheduled_at",{ascending:true}).limit(200);
if(filters.employee) query=query.eq("assigned_employee_id",filters.employee); if(filters.type) query=query.eq("follow_up_type",filters.type); if(filters.date){const start=new Date(`${filters.date}T00:00:00`); const end=new Date(`${filters.date}T23:59:59`); query=query.gte("scheduled_at",start.toISOString()).lte("scheduled_at",end.toISOString());} if(scopedCustomerIds) query=scopedCustomerIds.length?query.in("customer_id",scopedCustomerIds):query.eq("customer_id","00000000-0000-0000-0000-000000000000");
const {data,error}=await query; const rows=((data??[]) as any[]).map((f)=>({...f,displayStatus:getFollowUpDisplayStatus(f)})).filter((f)=>f.displayStatus===filters.status) as (FollowUpRow & {displayStatus:string;scheduled_at:string})[];
const emptyCopy=filters.status==="overdue"?{title:"لا توجد متابعات متأخرة",description:"جميع المتابعات ضمن المسار الصحيح"}:filters.status==="due_today"?{title:"لا توجد متابعات اليوم",description:"لا توجد متابعات مستحقة لهذا اليوم"}:{title:"لا توجد متابعات",description:"ستظهر المتابعات هنا بعد إضافتها للعملاء"};
return <div><PageHeader title="المتابعات" description="إدارة مواعيد التواصل مع العملاء حسب الحالة والموظف والفرع" actions={<Button asChild><Link href="/follow-ups/new"><CalendarPlus className="h-4 w-4" />إضافة متابعة</Link></Button>} />
<div className="mb-4 flex flex-wrap gap-2">{tabs.map((tab)=><Button key={tab.key} asChild size="sm" variant={filters.status===tab.key?"default":"outline"} className="rounded-full"><Link href={`/follow-ups?${new URLSearchParams({...Object.fromEntries(Object.entries(filters).filter(([,v])=>v)),status:tab.key} as Record<string,string>).toString()}`}>{tab.label}</Link></Button>)}</div>
<TableToolbar><form className="grid gap-3 md:grid-cols-3 xl:grid-cols-8"><div className="relative md:col-span-2"><Search className="pointer-events-none absolute right-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input name="q" defaultValue={filters.q} placeholder="بحث بالعميل أو رقم الجوال" className="pr-9" /></div><Select name="employeeId" defaultValue={filters.employee}><option value="">الموظف المسؤول</option>{(employeesResult.data??[]).map((e)=><option key={e.id} value={e.id}>{e.full_name}</option>)}</Select><Select name="branchId" defaultValue={filters.branch}><option value="">الفرع</option>{(branchesResult.data??[]).map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</Select><Select name="type" defaultValue={filters.type}><option value="">نوع المتابعة</option>{followUpTypes.map((t)=><option key={t} value={t}>{followUpTypeLabels[t]}</option>)}</Select><Select name="status" defaultValue={filters.status}><option value="">الحالة</option>{followUpStatuses.map((s)=><option key={s} value={s}>{followUpStatusLabels[s]}</option>)}</Select><Input name="date" defaultValue={filters.date} type="date" aria-label="التاريخ" /><div className="flex gap-2"><Button type="submit">تطبيق الفلاتر</Button><Button type="button" asChild variant="outline"><Link href="/follow-ups">إعادة تعيين</Link></Button></div></form></TableToolbar>
<DataTableShell>{error?<div className="p-6 text-sm text-destructive">تعذر تحميل بيانات المتابعات</div>:rows.length===0?<EmptyTableState icon={Clock3} title={emptyCopy.title} description={emptyCopy.description} />:<Table><TableHeader><TableRow className="bg-muted/20"><TableHead>العميل</TableHead><TableHead>رقم الجوال</TableHead><TableHead>الموظف المسؤول</TableHead><TableHead>نوع المتابعة</TableHead><TableHead>تاريخ المتابعة</TableHead><TableHead>الحالة</TableHead><TableHead>النتيجة</TableHead><TableHead className="text-left">الإجراءات</TableHead></TableRow></TableHeader><TableBody>{rows.map((f)=>{const isOver=f.displayStatus==="overdue"; const isToday=f.displayStatus==="due_today";return <TableRow key={f.id} className={`border-b-8 border-transparent hover:bg-muted/20 ${isOver?"bg-rose-50/40 dark:bg-rose-950/15":""} ${isToday?"bg-amber-50/40 dark:bg-amber-950/15":""}`}><TableCell><CustomerCell name={f.customers?.full_name ?? "غير محدد"} subtitle={isOver?"متابعة متأخرة":isToday?"مستحقة اليوم":""} /></TableCell><TableCell>{f.customers?.phone ?? "غير محدد"}</TableCell><TableCell>{f.profiles?.full_name ?? "غير محدد"}</TableCell><TableCell><Badge variant="secondary">{followUpTypeLabels[f.follow_up_type as keyof typeof followUpTypeLabels] ?? "أخرى"}</Badge></TableCell><TableCell>{formatSaudiDateTime(f.scheduled_at)}</TableCell><TableCell><FollowUpStatusBadge status={f.displayStatus} /></TableCell><TableCell>{f.result || "لا توجد نتيجة"}</TableCell><TableCell><RowActionButtons actions={[{label:"عرض",href:`/follow-ups/${f.id}`},{label:"إكمال المتابعة",href:`/follow-ups/${f.id}#complete`},{label:"إضافة متابعة جديدة",href:f.customers?.id?`/follow-ups/new?customer_id=${f.customers.id}`:"/follow-ups/new"},{label:"فتح العميل",href:f.customers?.id?`/customers/${f.customers.id}`:"/customers"}]} /></TableCell></TableRow>;})}</TableBody></Table>}</DataTableShell></div>;
}
