import Link from "next/link";
import { FilePlus2, Search } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { CustomerStatusBadge } from "@/components/status-badge";
import { CustomerCell, DataTableShell, EmptyTableState, RowActionButtons, TableToolbar } from "@/components/tables/operational-table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Select } from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { customerStatusLabels, customerStatuses, visitTypeLabels, visitTypes } from "@/constants/statuses";
import { requireUser } from "@/lib/auth";
import { formatSaudiDateTime } from "@/lib/format";
import { createClient } from "@/lib/supabase/server";

type VisitsPageProps = { searchParams?: Record<string, string | string[] | undefined> };
type VisitRow = { id:string; visit_datetime:string; visit_type:string; customer_status:string; next_follow_up_at:string|null; customers:{id:string; full_name:string; phone:string}|null; branches:{name:string}|null; profiles:{full_name:string}|null; interest_categories:{name:string}|null; };
function param(searchParams: VisitsPageProps["searchParams"], key: string) { const value = searchParams?.[key]; return Array.isArray(value) ? value[0] ?? "" : value ?? ""; }

export default async function VisitsPage({ searchParams }: VisitsPageProps) { await requireUser(); const supabase=createClient(); const filters={q:param(searchParams,"q"),branch:param(searchParams,"branchId")||param(searchParams,"branch"),employee:param(searchParams,"employeeId")||param(searchParams,"employee"),visitType:param(searchParams,"visitType")||param(searchParams,"visit_type"),category:param(searchParams,"category"),status:param(searchParams,"status"),date:param(searchParams,"date")};
const [branchesResult, employeesResult, categoriesResult]=await Promise.all([supabase.from("branches").select("id, name").eq("is_active",true).order("name"),supabase.from("profiles").select("id, full_name").eq("is_active",true).order("full_name"),supabase.from("interest_categories").select("id, name").eq("is_active",true).order("name")]);
let query=supabase.from("visits").select("id, visit_datetime, visit_type, customer_status, next_follow_up_at, customers(id, full_name, phone), branches(name), profiles!visits_sales_employee_id_fkey(full_name), interest_categories(name)").order("visit_datetime",{ascending:false}).limit(100);
if(filters.q) query=query.or(`customers.full_name.ilike.%${filters.q}%,customers.phone.ilike.%${filters.q}%`); if(filters.branch) query=query.eq("branch_id",filters.branch); if(filters.employee) query=query.eq("sales_employee_id",filters.employee); if(filters.visitType) query=query.eq("visit_type",filters.visitType); if(filters.category) query=query.eq("interest_category_id",filters.category); if(filters.status) query=query.eq("customer_status",filters.status); if(filters.date){const todayKey=filters.date==="today"?new Date().toISOString().slice(0,10):filters.date; const start=new Date(`${todayKey}T00:00:00`); const end=new Date(`${todayKey}T23:59:59`); query=query.gte("visit_datetime",start.toISOString()).lte("visit_datetime",end.toISOString());}
const {data,error}=await query; const rows=(data??[]) as unknown as VisitRow[];
return <div><PageHeader title="الزيارات" description="متابعة زيارات العملاء داخل المعارض حسب الفروع والموظفين والحالات" actions={<Button asChild><Link href="/visits/new"><FilePlus2 className="h-4 w-4" />تسجيل زيارة جديدة</Link></Button>} />
<TableToolbar><form className="grid gap-3 md:grid-cols-3 xl:grid-cols-8"><div className="relative md:col-span-2"><Search className="pointer-events-none absolute right-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input name="q" defaultValue={filters.q} placeholder="بحث بالعميل أو رقم الجوال" className="pr-9"/></div><Select name="branchId" defaultValue={filters.branch}><option value="">الفرع</option>{(branchesResult.data??[]).map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</Select><Select name="employeeId" defaultValue={filters.employee}><option value="">موظف المبيعات</option>{(employeesResult.data??[]).map((e)=><option key={e.id} value={e.id}>{e.full_name}</option>)}</Select><Select name="visitType" defaultValue={filters.visitType}><option value="">نوع الزيارة</option>{visitTypes.map((t)=><option key={t} value={t}>{visitTypeLabels[t]}</option>)}</Select><Select name="category" defaultValue={filters.category}><option value="">القسم</option>{(categoriesResult.data??[]).map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</Select><Select name="status" defaultValue={filters.status}><option value="">الحالة</option>{customerStatuses.map((s)=><option key={s} value={s}>{customerStatusLabels[s]}</option>)}</Select><Input name="date" defaultValue={filters.date==="today"?new Date().toISOString().slice(0,10):filters.date} type="date" aria-label="التاريخ" /><div className="flex gap-2"><Button type="submit">تطبيق الفلاتر</Button><Button asChild type="button" variant="outline"><Link href="/visits">إعادة تعيين</Link></Button></div></form></TableToolbar>
<DataTableShell>{error?<div className="p-6 text-sm text-destructive">تعذر تحميل بيانات الزيارات</div>:rows.length===0?<EmptyTableState icon={Search} title="لا توجد زيارات مسجلة" description="ابدأ بتسجيل زيارة جديدة لأحد العملاء" />:<Table><TableHeader><TableRow className="bg-muted/20"><TableHead>العميل</TableHead><TableHead>رقم الجوال</TableHead><TableHead>الفرع</TableHead><TableHead>موظف المبيعات</TableHead><TableHead>تاريخ الزيارة</TableHead><TableHead>نوع الزيارة</TableHead><TableHead>القسم</TableHead><TableHead>الحالة</TableHead><TableHead>موعد المتابعة</TableHead><TableHead className="text-left">الإجراءات</TableHead></TableRow></TableHeader><TableBody>{rows.map((v)=><TableRow key={v.id} className="border-b-8 border-transparent hover:bg-muted/20"><TableCell><CustomerCell name={v.customers?.full_name ?? "غير محدد"} subtitle={v.branches?.name ?? "غير محدد"} /></TableCell><TableCell>{v.customers?.phone ?? "غير محدد"}</TableCell><TableCell>{v.branches?.name ?? "غير محدد"}</TableCell><TableCell>{v.profiles?.full_name ?? "غير محدد"}</TableCell><TableCell>{formatSaudiDateTime(v.visit_datetime)}</TableCell><TableCell><Badge variant="secondary">{visitTypeLabels[v.visit_type as keyof typeof visitTypeLabels] ?? "غير محدد"}</Badge></TableCell><TableCell>{v.interest_categories?.name ?? "غير محدد"}</TableCell><TableCell><CustomerStatusBadge status={v.customer_status} /></TableCell><TableCell>{formatSaudiDateTime(v.next_follow_up_at)}</TableCell><TableCell><RowActionButtons actions={[{label:"عرض",href:`/visits/${v.id}`},{label:"فتح العميل",href:v.customers?.id?`/customers/${v.customers.id}`:"/customers"},{label:"إضافة متابعة",href:v.customers?.id?`/customers/${v.customers.id}#follow-up-form`:"/follow-ups/new"},{label:"تعديل",href:`/visits/${v.id}?edit=1`}]} /></TableCell></TableRow>)}</TableBody></Table>}</DataTableShell></div>;
}
