import Link from "next/link";
import { Eye, FilePlus2, Pencil, Plus, Search } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { CustomerStatusBadge, PurchaseProbabilityBadge } from "@/components/status-badge";
import { CustomerCell, DataTableShell, EmptyTableState, RowActionButtons, TableToolbar } from "@/components/tables/operational-table";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { customerStatusLabels, customerStatuses, purchaseProbabilities, purchaseProbabilityLabels } from "@/constants/statuses";
import { requireUser } from "@/lib/auth";
import { formatSaudiDateTime } from "@/lib/format";
import { createClient } from "@/lib/supabase/server";
// same types/functions
 type CustomersPageProps = { searchParams?: Record<string, string | string[] | undefined> };
 type CustomerRow = { id:string; full_name:string; phone:string; city:string|null; current_status:string; purchase_probability:string|null; updated_at:string|null; branches:{name:string}|null; profiles:{full_name:string}|null; lead_sources:{name:string}|null; };
const statusTabs=[{value:"",label:"الكل"},{value:"new",label:"جديد"},{value:"interested",label:"مهتم"},{value:"needs_follow_up",label:"يحتاج متابعة"},{value:"quotation_requested",label:"طلب عرض سعر"},{value:"sold",label:"تم البيع"}] as const;
function param(searchParams: CustomersPageProps["searchParams"], key: string) { const value = searchParams?.[key]; return Array.isArray(value) ? value[0] ?? "" : value ?? ""; }
export default async function CustomersPage({ searchParams }: CustomersPageProps) { await requireUser(); const supabase=createClient();
const filters={q:param(searchParams,"q"),branch:param(searchParams,"branch"),employee:param(searchParams,"employee"),category:param(searchParams,"category"),status:param(searchParams,"status"),source:param(searchParams,"source"),probability:param(searchParams,"probability"),createdFrom:param(searchParams,"created_from"),createdRange:param(searchParams,"createdRange")};
const [branchesResult, employeesResult, categoriesResult, sourcesResult] = await Promise.all([supabase.from("branches").select("id, name").eq("is_active", true).order("name"),supabase.from("profiles").select("id, full_name").eq("is_active", true).order("full_name"),supabase.from("interest_categories").select("id, name").eq("is_active", true).order("name"),supabase.from("lead_sources").select("id, name").eq("is_active", true).order("name")]);
let customerIdsByCategory:string[]|null=null; if(filters.category){const {data}=await supabase.from("visits").select("customer_id").eq("interest_category_id",filters.category);customerIdsByCategory=Array.from(new Set((data??[]).map((v)=>v.customer_id)));}
let query=supabase.from("customers").select("id, full_name, phone, city, current_status, purchase_probability, updated_at, created_at, branches(name), profiles!customers_assigned_employee_id_fkey(full_name), lead_sources(name)").order("updated_at",{ascending:false}).limit(100);
if(filters.q) query=query.or(`full_name.ilike.%${filters.q}%,phone.ilike.%${filters.q}%`); if(filters.branch) query=query.eq("branch_id",filters.branch); if(filters.employee) query=query.eq("assigned_employee_id",filters.employee); if(filters.status) query=query.eq("current_status",filters.status); if(filters.source) query=query.eq("source_id",filters.source); if(filters.probability) query=query.eq("purchase_probability",filters.probability); if(filters.createdFrom) query=query.gte("created_at",filters.createdFrom); if(filters.createdRange==="today"){const start=new Date(); start.setHours(0,0,0,0); const end=new Date(start); end.setDate(end.getDate()+1); query=query.gte("created_at",start.toISOString()).lt("created_at",end.toISOString());}
if(customerIdsByCategory){query=customerIdsByCategory.length?query.in("id",customerIdsByCategory):query.eq("id","00000000-0000-0000-0000-000000000000");}
const {data:customers,error}=await query; const rows=(customers??[]) as unknown as CustomerRow[]; const ids=rows.map((c)=>c.id);
const [visitsResult, followUpsResult]=ids.length?await Promise.all([supabase.from("visits").select("customer_id, visit_datetime").in("customer_id",ids).order("visit_datetime",{ascending:false}),supabase.from("follow_ups").select("customer_id, scheduled_at, status").in("customer_id",ids).neq("status","completed").order("scheduled_at",{ascending:true})]):[{data:[]},{data:[]}];
const latestVisitByCustomer=new Map<string,string>(); for(const v of visitsResult.data??[]) if(!latestVisitByCustomer.has(v.customer_id)) latestVisitByCustomer.set(v.customer_id,v.visit_datetime);
const nextFollowUpByCustomer=new Map<string,string>(); for(const f of followUpsResult.data??[]) if(!nextFollowUpByCustomer.has(f.customer_id)) nextFollowUpByCustomer.set(f.customer_id,f.scheduled_at);
return <div><PageHeader title="العملاء" description="إدارة العملاء المسجلين ومتابعة حالاتهم واهتماماتهم" actions={<><Button asChild variant="outline"><Link href="/visits/new"><FilePlus2 className="h-4 w-4" />تسجيل زيارة جديدة</Link></Button><Button asChild><Link href="/customers/new"><Plus className="h-4 w-4" />إضافة عميل</Link></Button></>} />
<div className="mb-4 flex flex-wrap gap-2">{statusTabs.map((tab)=><Button key={tab.value||"all"} asChild size="sm" variant={filters.status===tab.value?"default":"outline"} className="rounded-full"><Link href={`/customers?${new URLSearchParams({...Object.fromEntries(Object.entries(filters).filter(([,v])=>v)),status:tab.value} as Record<string,string>).toString()}`}>{tab.label}</Link></Button>)}</div>
<TableToolbar><form className="grid gap-3 md:grid-cols-3 xl:grid-cols-8"><div className="relative md:col-span-2"><Search className="pointer-events-none absolute right-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input name="q" defaultValue={filters.q} placeholder="بحث بالاسم أو رقم الجوال" className="pr-9" /></div><Select name="branch" defaultValue={filters.branch}><option value="">الفرع</option>{(branchesResult.data??[]).map((branch)=><option key={branch.id} value={branch.id}>{branch.name}</option>)}</Select><Select name="employee" defaultValue={filters.employee}><option value="">موظف المبيعات</option>{(employeesResult.data??[]).map((e)=><option key={e.id} value={e.id}>{e.full_name}</option>)}</Select><Select name="category" defaultValue={filters.category}><option value="">القسم المهتم</option>{(categoriesResult.data??[]).map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</Select><Select name="status" defaultValue={filters.status}><option value="">الحالة</option>{customerStatuses.map((s)=><option key={s} value={s}>{customerStatusLabels[s]}</option>)}</Select><Select name="source" defaultValue={filters.source}><option value="">مصدر العميل</option>{(sourcesResult.data??[]).map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</Select><Select name="probability" defaultValue={filters.probability}><option value="">احتمالية الشراء</option>{purchaseProbabilities.map((p)=><option key={p} value={p}>{purchaseProbabilityLabels[p]}</option>)}</Select><Input name="created_from" defaultValue={filters.createdFrom} type="date" aria-label="تاريخ الإنشاء" /><div className="flex gap-2"><Button type="submit">تطبيق الفلاتر</Button><Button type="button" asChild variant="outline"><Link href="/customers">إعادة تعيين</Link></Button></div></form></TableToolbar>
<DataTableShell>{error?<div className="p-6 text-sm text-destructive">تعذر تحميل بيانات العملاء</div>:rows.length===0?<EmptyTableState icon={Search} title="لا يوجد عملاء" description="ابدأ بإضافة أول عميل أو تسجيل زيارة جديدة" />:<Table><TableHeader><TableRow className="bg-muted/20"><TableHead>العميل</TableHead><TableHead>رقم الجوال</TableHead><TableHead>الفرع</TableHead><TableHead>موظف المبيعات</TableHead><TableHead>الحالة</TableHead><TableHead>احتمالية الشراء</TableHead><TableHead>آخر زيارة</TableHead><TableHead>موعد المتابعة</TableHead><TableHead className="text-left">الإجراءات</TableHead></TableRow></TableHeader><TableBody>{rows.map((c)=><TableRow key={c.id} className="border-b-8 border-transparent hover:bg-muted/20"><TableCell><CustomerCell name={c.full_name} subtitle={c.city ?? "بدون مدينة"} /></TableCell><TableCell>{c.phone}</TableCell><TableCell>{c.branches?.name ?? "غير محدد"}</TableCell><TableCell>{c.profiles?.full_name ?? "غير محدد"}</TableCell><TableCell><CustomerStatusBadge status={c.current_status} /></TableCell><TableCell><PurchaseProbabilityBadge probability={c.purchase_probability} /></TableCell><TableCell>{formatSaudiDateTime(latestVisitByCustomer.get(c.id))}</TableCell><TableCell>{formatSaudiDateTime(nextFollowUpByCustomer.get(c.id))}</TableCell><TableCell><RowActionButtons actions={[{label:"عرض",href:`/customers/${c.id}`},{label:"تعديل",href:`/customers/${c.id}?edit=1`},{label:"إضافة متابعة",href:`/customers/${c.id}#follow-up-form`},{label:"تسجيل زيارة",href:`/visits/new?customer_id=${c.id}`}]}/></TableCell></TableRow>)}</TableBody></Table>}</DataTableShell></div>;
}
